IssueManagementSystem/IssueManagementSystem/Controllers/SupervisorController.cs
using IssueManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Threading;
using System.Net.Mime;
using Newtonsoft.Json.Linq;
using System.Collections;
using IssueManagementSystem.Models.IssueManagementSystem.Models;

namespace IssueManagementSystem.Controllers
{
    public class SupervisorController : Controller
    {

        Communication com = new Communication();
        // GET: Supervisor
        public ActionResult selectIssue(int lineid)// select issue view
        {
            ViewBag.lineid = lineid;

            if ((Session["userID"] == null) || ((string)Session["Role"] != "supervisor"))
            {
                return RedirectToAction("Index", "Login");

            }
        
            return View();
        }

        [HttpGet]
        public JsonResult GetIssues()
        {
            return Json(IssueService.GetIssue(), JsonRequestBehavior.AllowGet);

        }
       [HttpGet]
        public JsonResult GetBreakedown()
        {
          return Json(BreakeDownService.GetBreakedown(), JsonRequestBehavior.AllowGet);

       }

        public ActionResult MachinBreakdown(int lineid)//machine breakedown view
        {
            ViewBag.lineid = lineid;
            if ((Session["userID"] == null) || ((string)Session["Role"] != "supervisor"))
            {
                return RedirectToAction("Index", "Login");

            }
         
            return View();
        }
        public ActionResult QualityIssue(int lineid)//Qulity view
        {
            ViewBag.lineid = lineid;
            if ((Session["userID"] == null) || ((string)Session["Role"] != "supervisor"))
            {
                return RedirectToAction("Index", "Login");

            }
            return View();
        }

        public ActionResult TechnicalIssue(int lineid)//Technical Issue View
        {
            ViewBag.lineid = lineid;
            if ((Session["userID"] == null) || ((string)Session["Role"] != "supervisor"))
            {
                return RedirectToAction("Index", "Login");

            }
          
            return View();
        }

        public ActionResult MaterialDelay(int lineid)//MaterialDelay View
        {
            ViewBag.lineid = lineid;
            if ((Session["userID"] == null) || ((string)Session["Role"] != "supervisor"))
            {
                return RedirectToAction("Index", "Login");
            }

            dynamic jobCardsList = new System.Dynamic.ExpandoObject();
            FLINTEC_Prod_Order_Line_Context jobCardContext = new FLINTEC_Prod_Order_Line_Context();
            List<FLINTEC_Prod_Order_Line> jcList = jobCardContext.FLINTEC_Prod_Order_Line.Where(x => x.Status == 3).ToList();
            jobCardsList.jobCards = jcList;
            return View(jobCardsList);
        }


        public ActionResult loadMaterialList(string selectedJobCard)
        {
            dynamic materials = new System.Dynamic.ExpandoObject();
            FLINTEC_Prod_Order_Component_Context jobCardContext = new FLINTEC_Prod_Order_Component_Context();
            List<FLINTEC_Prod_Order_Component> matList = jobCardContext.FLINTEC_Prod_Order_Component.Where(x => (x.Prod_Order_No_.Equals(selectedJobCard))).ToList();
            materials.materials = matList;
            return Json(materials);
        }
        public ActionResult ITIssue(int lineid)//IT Issue view
        {
            ViewBag.lineid = lineid;
            if ((Session["userID"] == null) || ((string)Session["Role"] != "supervisor"))
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        [HttpPost] //add Breakedown to database
        public ActionResult AddIssueBreakedown(issue_occurrence issueModel, string issueJson, notification_handling notification_HandlingModel)
        {
            var time = DateTime.Now;
            string current_time = time.ToString("yyyy-MM-dd HH:mm");//get today to string variable
        
            using (issue_management_systemEntities1 db = new issue_management_systemEntities1())
            {
                if (ModelState.IsValid)
                {
                    JArray issueData = JArray.Parse(issueJson) as JArray;
                    System.Diagnostics.Debug.WriteLine(issueData);

                    var date = DateTime.ParseExact(current_time, "yyyy-MM-dd HH:mm", System.Globalization.CultureInfo.InvariantCulture);
                    var dayitem = current_time.Split(' ');
                    var day = dayitem[0];
                    var time1 = dayitem[1];
                    var HHMM = time1.Split(':');
                    try
                    {

                        foreach (JObject item in issueData)
                        {
                            int line_id = Int32.Parse(item["line_line_id"].ToString());
                            int issue_id = 1;
                            string group = item["group"].ToString();
                            var resp_person = db.issue_line_person.Where(x => x.levelOfResponsibility == 1 && x.line_id == line_id && x.issue_id == issue_id && x.person_level == 1).FirstOrDefault();
                            var responsible_person_emp_id = resp_person.EmployeeNumber; //get certain employee assigned for a certain issue in a certain line and the level of resp. should be one
                            issueModel.machine_machine_id = item["machine"].ToString();
                            issueModel.line_line_id = line_id;
                            issueModel.responsible_person_confirm_status = 1;
                            issueModel.department = "Maintenance";
                            issueModel.issue_satus = "1";
                            issueModel.loged_by = Int32.Parse(item["empId"].ToString());
                               
                            issueModel.issue_issue_ID = 1;//Issue id is 1 for Breakdown
                            issueModel.responsible_person_emp_id = resp_person.EmployeeNumber;
                            issueModel.location = item["location"].ToString();
                            issueModel.description = item["description"].ToString();
                            if (group != "") { issueModel.group = Int32.Parse(item["group"].ToString()); }
                            
                            issueModel.issue_date = date;
                            


                            string machine = issueModel.machine_machine_id;
                            var respPersonID = db.issue_line_person.Where(x => x.line_id == line_id && x.levelOfResponsibility == 1 && x.issue_id == 1 && x.person_level == 1).FirstOrDefault();
                            issueModel.responsible_person_emp_id = Int32.Parse(respPersonID.EmployeeNumber.ToString());
                            db.issue_occurrence.Add(issueModel);
                            db.SaveChanges();// end of the save

                            var issue_occour_id = issueModel.issue_occurrence_id;

                            if (issueModel.issue_occurrence_id > 0)
                            {
                                var line = db.lines.Where(x => x.line_id == line_id).FirstOrDefault();
                                string msg = " Breakdown has occurred.@@ Line : " + line.line_name + " Line @ Date : " + day + " @ Time : " + time1 + " @ Machine : " + machine + " @ Note : " + issueModel.description;
                              
                                string callNote = line.line_name + " line Breakdown has occurred at " + time1;
                                var displayInfo = db.displays.Where(x => x.line_id == line_id).FirstOrDefault();
                               
                                //turn on the Light
                                if (group == "") { com.lightON("1", displayInfo.raspberry_ip_address); 
                                }
                                else if (group != "") {
                                    com.lightONMachineshop("1", displayInfo.raspberry_ip_address, group );
                                    callNote = line.line_name + " Breakdown has occurred at " + time1;
                                    msg = " Breakdown has occurred.@@ Area : " + line.line_name + " @ Date : " + day + " @ Time : " + time1 + " @ Machine : " + machine + " @ Note : " + issueModel.description;

                                }


                               com.maintenancesbuzzerOn(item["location"].ToString());
                                msg = msg.Replace("@", Environment.NewLine);
                                ModelState.Clear();
                                sendCD(line_id, 1, msg, "Machine Breakdown has occurred", callNote, issue_occour_id, notification_HandlingModel);
                               
                            }
                            
                        }

                    }
                    catch (Exception ex)
                    {
                        return Content("Error Occured" + ex.ToString(), MediaTypeNames.Text.Plain);

                    }

                }
            }
            return Content("Breakedown Issue Recorded", MediaTypeNames.Text.Plain);
        }

        [HttpPost]//add Tecnical Issues to database
        public ActionResult AddIssueTechnical(string issueJson, issue_occurrence issueModel, notification_handling notification_HandlingModel)
        {
            var time = DateTime.Now;
            string current_time = time.ToString("yyyy-MM-dd HH:mm");

            using (issue_management_systemEntities1 db = new issue_management_systemEntities1())
            {
                if (ModelState.IsValid)
                {
                    JArray issueData = JArray.Parse(issueJson) as JArray;
                    System.Diagnostics.Debug.WriteLine(issueData);

IssueManagementSystem/IssueManagementSystem/Views/Supervisor/ITIssue.cshtml
@{
    /**/
    ViewBag.Title = "ITIssue";
    Layout = "~/Views/Shared/supervisorsLayout.cshtml";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
    ViewBag.rol = Session["Role"];
    int userID = (int)Session["userID"];// get current supervisorID


    int lineId = ViewBag.lineid;
}
@using IssueManagementSystem.Models
@model IssueManagementSystem.Models.issue_occurrence
<link href="~/Content/SupervisorStyles/supervisorStyle.css" rel="stylesheet" />


<div class="container margin ">

    <link href="~/Content/SupervisorStyles/supervisorStyle.css" rel="stylesheet" />
    <link href="~/Content/googlegrafics.css" rel="stylesheet" />
    <link href="~/Content/adminstyles/select2-min.css" rel="stylesheet" />
    <link href="~/Content/adminstyles/Settings.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <h2>IT Issue</h2>
    <hr />
    <div class="row">
        <div class="" style="width:50%;margin:auto;">
            <div class="form-group" style="width:100%;margin:auto">
                <span id="lineID" style="display:none">@lineId</span>



                <div style="padding-top:20px;margin-top:5%">
                    <label for="exampleFormControlTextarea1">Description</label>
                    <textarea class="form-control" rows="5" id="description" spellcheck="true"></textarea>
                </div>

                <div class="button-holder" style="display:block">
                    <div class="ajax-button">
                        <div class="fa fa-check done"></div>
                        <div class="fa fa-close failed"></div>
                        <input id="submit" class="submit" type="submit" value="Submit" />
                    </div>
                </div>

            </div>
        </div>
    </div>


</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script src="~/Scripts/AdminScripts/jscolar.js"></script>
<script src="~/Scripts/AdminScripts/select2-min.js"></script>
<script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>
<script src="~/signalr/Hubs"></script>
<script>

    $("#submit").click(function () {
        obj = new Object();
        obj.description = document.getElementById("description").value;
        obj.line_line_id = @ViewBag.lineid;
        obj.location =  '@Session["location"]';
       obj.empId=@Session["userID"]
        var obj_array = new Array();
        obj_array.push(obj);
        var issueJson = JSON.stringify(obj_array);
         var url = '@Url.Action("AddIssueIT", "Supervisor")'
        $.ajax({
            type: "POST",
            dataType: 'text',
            url: url,
            data: { issueJson: issueJson },
            success: function (feedback) {
               $.connection.hub.start()//Refresh Screen
                .done(function () {
                 console.log("Worked")
                 $.connection.ismHub.server.announce();
              }).fail(function () { alert("Can't Refresh Your Line Screen! Plese Inform IT Department!") });//return to dashbord
              window.location.href = '@Url.Action("selectIssue", "Supervisor")?lineid=@ViewBag.lineId';
            },
            error: function (feedback) {
                alert(feedback);
            }
        });
    });
   $('#groups').select2({
        placeholder: "Select Group.....",
        allowClear: false
    });
</script>

IssueManagementSystem/IssueManagementSystem/Views/Supervisor/MachinBreakdown.cshtml
@using IssueManagementSystem.Models;
@model IssueManagementSystem.Models.issue_occurrence
@{
    ViewBag.Title = "MachinBreakdown";
    Layout = "~/Views/Shared/supervisorsLayout.cshtml";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }

    ViewBag.rol = Session["Role"];
    int userID = (int)Session["userID"];// get current supervisorID
    int lineId = ViewBag.lineid;
    using (issue_management_systemEntities1 db = new issue_management_systemEntities1())//method for load the map acordinto the surevisor line
    {

        var mapInfo = db.line_map.Where(y => y.line_id == lineId).FirstOrDefault();
        ViewData["map"] = mapInfo.map.ToString().Trim();//get the map arry to ViewData

    }
    BigRedEntities imsDbContext = new BigRedEntities();
    List<tblWorkstation_Config> mList = imsDbContext.tblWorkstation_Config.ToList();
}




<link href="~/Content/SupervisorStyles/supervisorStyle.css" rel="stylesheet" />
<link href="~/Content/adminstyles/select2-min.css" rel="stylesheet" />


<div class="container" style="margin-top:20px">
    <h2>Machine Breakdown</h2>
    <hr />
    <h5 id="selectMachine">Select the machine</h5>

    <input type="hidden" value="@Session["userID"]" id="userId" />
    <div class="row">

        <div class="col-md-3" id="mapdiv">
            <div class="container-liquid" >
                <div style="display:inline-grid;grid-template-columns: 90%  50%">
                    <div id="container">
                        <canvas id="canvas1" style="border: 1px solid black;background-size: 100% 100%;" width="250" height="750">
                            <br />This text is displayed if your browser does not support HTML5 Canvas.
                        </canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 machine" id="inputs">
            <div id="groupsdiv" style="margin-top:5%">
                <label for="exampleFormControlTextarea1" >Select Area</label>
                <select class="js-example-placeholder-single js-states form-control" id="groups" name="Material" style="width:100%;">
                    <option></option>

                </select>
            </div>

            <div id="machinediv" style="margin-top:5%">
                <label for="exampleFormControlTextarea1">Select Machine</label>
                <select class="js-example-placeholder-single js-states form-control" id="machineSelect" name="Material" style="width:100%;" onchange="">
                    <option></option>
                    @foreach (var item in mList)
                    {
                        <option value="@item.Machine_ID">@item.Machine_ID</option>
                    }
                </select>
            </div>
            <div class="form-group machine" id="machineText" style="margin-top:5%">
                <label for="exampleFormControlTextarea1">Machine</label>
                <input type="text" class="form-control" id="machine" disabled>
            </div>
            <label id="map" style="display: none;">@ViewData["map"]</label>

            <div id="machineshopdiv">
                <label for="exampleFormControlTextarea1" style="margin-top:5%">Group</label>
                <input type="text" class="form-control" id="grouptext" disabled>
            </div>
            <div class="form-group machine" style="margin-top:5%">
                <label for="exampleFormControlTextarea1">Extra Information</label>
                <textarea class="form-control" rows="4" id="description" spellcheck="true"></textarea>
            </div>
            <div class="container-fluid row" style="margin-left:30%">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 button-holder">
                            <div class="ajax-button">
                                <div class="fa fa-check done"></div>
                                <div class="fa fa-close failed"></div>
                                <input id="submit" class="submit" type="submit" value="Submit" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="~/Scripts/SupervisorScripts/showmap.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/Manager/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-toggle.min.js"></script>
    <script src="~/Scripts/AdminScripts/jscolar.js"></script>
    <script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>
    <script src="~/Scripts/AdminScripts/select2-min.js"></script>
    <script src="~/signalr/Hubs"></script>
    <script src="~/Scripts/SupervisorScripts/machineBrakedown.js"></script>

    <script>
      $('#groups').select2({
        placeholder: "Select Group.....",
        allowClear: false
    });
       $('#groupsdiv').hide()
       $('#machineshopdiv').hide()
       $('#machinediv').hide()
    if('@Session["department"]'=='MachineShop')
    {
      $('#machineshopdiv').show()
    }
    if((@ViewBag.lineid==9)||(@ViewBag.lineid==10))
    {
        $('#groups').append('<option value="1">Heat treatment</option>')
        $('#groups').append('<option value="2">Accessories</option>')
        $('#groupsdiv').show()
        $('#machineshopdiv').hide()
    }
   $("#submit").click(function () {
         var selectedDep = $('#groups').find(":selected").text();
        obj = new Object();
         obj.empId=@Session["userID"]
        obj.description = document.getElementById("description").value;
          if(selectedDep=='Accessories')//if selected department is Accessories
          {
          obj.machine = document.getElementById("machineSelect").value;
          }else{
         obj.machine = document.getElementById("machine").value;
          }
        obj.line_line_id = @ViewBag.lineid;
        obj.location =  '@Session["location"]';
        var grouparry=document.getElementById("grouptext").value.split(" ")
        if(grouparry=="")
        {
         obj.group=document.getElementById("groups").value
        }else{
        obj.group=grouparry[1];
        }
        var obj_array = new Array();
        obj_array.push(obj);
        var issueJson = JSON.stringify(obj_array);
         var url = '@Url.Action("AddIssueBreakedown", "Supervisor")'
        $.ajax({
            type: "POST",
            dataType: 'text',
            url: url,
            data: { issueJson: issueJson },
            success: function (feedback) {
               $.connection.hub.start()//Refresh Screen
                .done(function () {
                 console.log("Worked")
                 $.connection.ismHub.server.announce();
              }).fail(function () { alert("Can't Refresh Your Line Screen! Plese Inform IT Department!") });//return to dashbord
              window.location.href = '@Url.Action("selectIssue", "Supervisor")?lineid=@ViewBag.lineId'; //return to dashbord
            },
            error: function (feedback) {
                alert(feedback);
            }
        });
    });
      $(function() {
      $('#groups').change(function(){
       if( $(this).val()=='2')
        {
         $('#mapdiv').hide()
         $('#machineText').hide()
         $('#machinediv').show()
         $('#selectMachine').hide()
         $('#inputs').css('margin','auto');
        }else{
        $('#mapdiv').show()
        $('#machineText').show()
         $('#machinediv').hide()
        $('#selectMachine').show()
         $('#inputs').css('margin','');
        }
      });
    });
    var id=@ViewBag.lineid;
    var inputPath="../Content/images/"+id+".jpg"
    var url = '@Url.Action("loadBase64Image", "Admin")';
    $.ajax({
    type: "POST",
    dataType: 'text',
    url: url,
    data: {inputPath},
    success: function (mapData) {
    if (mapData.length > 0) {
    document.getElementById('canvas1').style.background = "url(data:image/jpeg;base64," + mapData + ")";
    }
    else {
    document.getElementById('canvas1').style.background = "";
    }
    document.getElementById('canvas1').style.backgroundSize = "250px 750px";
    },
    error: function () {
    alert("Error");
    }
    });
    $('#machineSelect').select2({
    placeholder: "Select Machine.....",
    });
    function  getMachineGroup(machine)
    {
      if('@Session["department"]'=='MachineShop')
        {
        var url = '@Url.Action("getMachine", "Supervisor")'
        $.ajax({
            type: "POST",
            dataType: 'text',
            url: url,
            data: {machine},
            success: function (feedback) {
             document.getElementById("grouptext").value=feedback
            },
            error: function (feedback) {

             }
          });
        }
    }
    </script>

</div>

IssueManagementSystem/IssueManagementSystem/Views/Supervisor/QualityIssue.cshtml
@using IssueManagementSystem.Models
@{
    /**/
    ViewBag.Title = "ITIssue";
    Layout = "~/Views/Shared/supervisorsLayout.cshtml";
    if (Session["userID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
    int lineId = ViewBag.lineid;
    using (issue_management_systemEntities1 db = new issue_management_systemEntities1())//method for load the map acordinto the surevisor line
    {

        var mapInfo = db.line_map.Where(y => y.line_id == lineId).FirstOrDefault();
        ViewData["map"] = mapInfo.map.ToString().Trim();//get the map arry to ViewData

    }
}

@model IssueManagementSystem.Models.issue_occurrence
<link href="~/Content/SupervisorStyles/supervisorStyle.css" rel="stylesheet" />

<div class="container margin ">
    <link href="~/Content/adminstyles/select2-min.css" rel="stylesheet" />
    <h2>Quality Issue</h2>
    <hr />
    <label id="map" style="display: none;">@ViewData["map"]</label>
    <div class="row">
        <div class="col-sm-4">
            <div class="container-liquid" id="mapdiv">
                <div style="display:inline-grid;grid-template-columns: 90%  50%">
                    <div id="container">
                        <canvas id="canvas1" style="border: 1px solid black;margin-left:8.2em;background-size: 100% 100%;" width="250" height="750">
                            <br>This text is displayed if your browser does not support HTML5 Canvas.<br>
                        </canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="" style="width:50%;margin:auto;">
            <div class="form-group" style="width:100%;margin:auto">
                <div id="groupsdiv">
                    <label for="exampleFormControlTextarea1" style="margin-top:5%">Select Area</label>
                    <select class="js-example-placeholder-single js-states form-control" id="groups" name="Material" style="width:100%;" onchange="">
                        <option></option>

                    </select>
                </div>
                <div class="form-group machine" id="machinediv">
                    <label for="exampleFormControlTextarea1">Machine</label>
                    <input type="text" class="form-control" id="machine" disabled>
                </div>
                <div id="machineshopdiv">
                    <label for="exampleFormControlTextarea1" style="margin-top:5%">Group</label>
                    <input type="text" class="form-control" id="grouptext" disabled>
                </div>
                <div style="padding-top:20px;margin-top:5%">
                    <label for="exampleFormControlTextarea1">Description</label>
                    <textarea class="form-control" rows="5" id="description" spellcheck="true"></textarea>
                </div>
                <div class="button-holder" style="display:block">
                    <div class="ajax-button">
                        <div class="fa fa-check done"></div>
                        <div class="fa fa-close failed"></div>
                        <input id="submit" class="submit" type="submit" value="Submit" />
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/SupervisorScripts/showmap.js"></script>
<script src="~/Scripts/AdminScripts/jscolar.js"></script>
<script src="~/Scripts/AdminScripts/select2-min.js"></script>
<script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>
<script src="~/signalr/Hubs"></script>

<script>
       $('#groupsdiv').hide()
     $('#mapdiv').hide()
     $('#machineshopdiv').hide()
    $('#machinediv').hide()
    if('@Session["department"]'=='MachineShop')
    {
      $('#mapdiv').show()
      $('#machineshopdiv').show()
      $('#machinediv').show()
    }
     if((@ViewBag.lineid==9)||(@ViewBag.lineid==10))
    {
        $('#groups').append('<option value="1">Heat treatment</option>')
        $('#groups').append('<option value="2">Accessories</option>')
        $('#groupsdiv').show()
        $('#mapdiv').hide()
        $('#machineshopdiv').hide()
        $('#machinediv').hide()
    }
  $("#submit").click(function () {
      obj = new Object();
        obj.description = document.getElementById("description").value;
        obj.line_line_id = @ViewBag.lineid;
        obj.location =  '@Session["location"]';
        obj.machine = document.getElementById("machine").value;
        obj.empId=@Session["userID"]
       var grouparry=document.getElementById("grouptext").value.split(" ")
        if(grouparry=="")
        {
          obj.group=document.getElementById("groups").value
        }else{
        obj.group=grouparry[1];
        }

        var obj_array = new Array();
        obj_array.push(obj);
        var issueJson = JSON.stringify(obj_array);
        var url = '@Url.Action("AddIssueQuality", "Supervisor")'
            $.ajax({
            type: "POST",
            dataType: 'text',
            url: url,
            data: { issueJson: issueJson },
            success: function (feedback) {
               $.connection.hub.start()//Refresh Screen
                .done(function () {
                 console.log("Worked")
                 $.connection.ismHub.server.announce();
              }).fail(function () { alert("Can't Refresh Your Line Screen! Plese Inform IT Department!") });//return to dashbord
              window.location.href = '@Url.Action("selectIssue", "Supervisor")?lineid=@ViewBag.lineId';
            },
            error: function (feedback) {
                alert(feedback);
            }
        });
    });
      $('#groups').select2({
        placeholder: "Select Area.....",
        allowClear: false
    });
       var id=@Session["lineId"];
    var inputPath="../Content/images/"+id+".jpg"
    var url = '@Url.Action("loadBase64Image", "Admin")';
    $.ajax({
    type: "POST",
    dataType: 'text',
    url: url,
    data: {inputPath},
    success: function (mapData) {
    if (mapData.length > 0) {
    document.getElementById('canvas1').style.background = "url(data:image/jpeg;base64," + mapData + ")";
    }
    else {
    document.getElementById('canvas1').style.background = "";
    }
    document.getElementById('canvas1').style.backgroundSize = "250px 750px";
    },
    error: function () {
    alert("Error");
    }
    });

    function  getMachineGroup(machine)
    {
      if('@Session["department"]'=='MachineShop')
        {
        var url = '@Url.Action("getMachine", "Supervisor")'

        $.ajax({
            type: "POST",
            dataType: 'text',
            url: url,
            data: {machine},
            success: function (feedback) {

               document.getElementById("grouptext").value=feedback

            },
            error: function (feedback) {
                alert(feedback);
             }
          });
        }
    }
</script>